# Generated by Django 3.2.9 on 2021-11-04 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='s_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='s_test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.JSONField()),
                ('answer', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skiff.s_user')),
            ],
        ),
        migrations.CreateModel(
            name='s_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skiff.s_user')),
            ],
        ),
        migrations.CreateModel(
            name='s_course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_open', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skiff.s_group')),
                ('s_test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skiff.s_test')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to='skiff.s_user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='skiff.s_user')),
            ],
        ),
    ]
