# Generated by Django 3.2.9 on 2021-11-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skiff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skiff.s_user'),
        ),
    ]
