# Generated by Django 3.2.9 on 2021-11-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skiff', '0002_alter_s_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_course',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skiff.s_group'),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='s_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skiff.s_test'),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='skiff.s_user'),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='skiff.s_user'),
        ),
        migrations.AlterField(
            model_name='s_test',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skiff.s_user'),
        ),
    ]
