# Generated by Django 3.2.9 on 2021-11-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skiff', '0003_auto_20211104_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_test',
            name='name',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skiff.s_group'),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='s_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skiff.s_test'),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to='skiff.s_user'),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='skiff.s_user'),
        ),
        migrations.AlterField(
            model_name='s_group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='s_group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skiff.s_user'),
        ),
        migrations.AlterField(
            model_name='s_test',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skiff.s_user'),
        ),
        migrations.AlterField(
            model_name='s_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='s_user',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
