# Generated by Django 3.2.9 on 2021-11-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skiff', '0004_auto_20211104_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_course',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skiff.s_group'),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='s_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skiff.s_test'),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='skiff.s_user'),
        ),
        migrations.AlterField(
            model_name='s_course',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='skiff.s_user'),
        ),
        migrations.AlterField(
            model_name='s_group',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skiff.s_user'),
        ),
        migrations.AlterField(
            model_name='s_test',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skiff.s_user'),
        ),
    ]
