# Generated by Django 3.2.9 on 2021-11-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skiff', '0005_auto_20211104_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_course',
            name='group',
        ),
        migrations.RemoveField(
            model_name='s_course',
            name='s_test',
        ),
        migrations.RemoveField(
            model_name='s_course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='s_course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='s_group',
            name='user',
        ),
        migrations.RemoveField(
            model_name='s_test',
            name='author',
        ),
    ]
