# Generated by Django 3.2.9 on 2021-11-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiff', '0006_auto_20211104_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_course',
            name='group',
            field=models.ManyToManyField(to='skiff.s_group'),
        ),
        migrations.AddField(
            model_name='s_course',
            name='s_test',
            field=models.ManyToManyField(to='skiff.s_test'),
        ),
        migrations.AddField(
            model_name='s_course',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='skiff.s_user'),
        ),
        migrations.AddField(
            model_name='s_course',
            name='user',
            field=models.ManyToManyField(related_query_name='student', to='skiff.s_user'),
        ),
        migrations.AddField(
            model_name='s_group',
            name='user',
            field=models.ManyToManyField(to='skiff.s_user'),
        ),
        migrations.AddField(
            model_name='s_test',
            name='author',
            field=models.ManyToManyField(to='skiff.s_user'),
        ),
    ]
