# Generated by Django 3.2.9 on 2021-11-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiff', '0007_auto_20211104_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('s_test', models.ManyToManyField(to='skiff.s_test')),
            ],
        ),
    ]
