# Generated by Django 3.2.9 on 2021-11-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiff', '0008_s_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_module',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
